user_idへの変更
hiroshi-iwata/notification pull request #3
Opened 2023-11-08 09:20 UTC by hiroshi-iwata

2023-11-09 09:03 UTC, srsm2000 commented on app/controllers/notifications_controller.rb
> +  before_action :correct_user, only: :index
> 一覧なのでshowではない気がしますがいかがでしょう？

indexに変更をいたしました。

2023-11-09 09:05 UTC, srsm2000 commented
確認します！
ちなみに次回からで良いので、files changedに↓こんな感じで書いてもらえると画面行き来しなくてレビュアーは助かります！
https://github.com/hiroshi-iwata/notification/pull/3/files#r1387687993

2023-11-09 10:20 UTC, srsm2000 requested changes
@hiroshi-iwata 色々コメント書きましたがめちゃくちゃ良くなっています。コードから何をしようとしているのかが伝わってきます！
引き続きよろしくです。

2023-11-09 10:20 UTC, srsm2000 commented on config/routes.rb
> +  resources :notifications,       only: [:index, :update]
> notification_controllerでparams[:id]だとnotificationのidかと錯覚されるので、user_idとかにすると良いかと！
> →
> user_idに変更しました。
> こちらの修正をしている際に、config/routes.rb内の
> get '/notifications/:user_id', to:"notifications#index"
> resources :notifications,       only: [:index, :update]
> どちらかは消しても問題ないのかと思っていたのですが、どちらを消してもエラーが出てしまいました。
> :user_idを使っているのかと思っていますが、もし原因をご存知でしたら教えてもらえると幸いです。

答えになっているかわかりませんが、resourcesのindexはuser_idを取得しないので
```get '/notifications/:user_id', to:"notifications#index"```と
```resources :notifications,       only: [:index]```
は違うものです！今回やりたいことをするには前者を使う必要がありそうです。

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +      "created_at >= ? AND user_id = ? AND action IN (?)",
> 読みやすさ等のため、SQLべた書きは避けることが多い
> →
> 修正して頂いていることに気づかず、自分なりの修正をしてしまいました🙇
> ただ、見やすさの面で言えばこちらも良いかと思ったので確認していただきたいです。

間違いという訳じゃないのですが、Active Recordのクエリメソッドで表現できるものをSQLで書くことはレアケースです。slcでも指摘されることが多いので書き換えた方が良いかなと思います。（書き換えても見づらいということはないはず）

2023-11-09 10:20 UTC, srsm2000 commented on app/controllers/notifications_controller.rb
> +    redirect_to controller: 'notifications', action: 'index', id: 'notifications.user_id'
存在しないid: に渡してますが動きますかね？

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +  scope :recent_follow, -> (notification_interval, user) {
userに紐づくnotificationはuser.notificationsで取れるので、現状引数にuserを取る必要がない気がします。

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
>    default_scope -> { order(created_at: :desc) }
default_scopeでググると、使い方によっては危険という記事が複数出てきますので見てみてください。
ちなみにこの実装は良いと思います！

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +  def self.create_follow_notification(user, current_user)
user, current_userという引数だと、どちらがフォローしたユーザーなのかがわかりにくいかなと思いました。

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +      if notification_first?(user) || is_time_expired?(user)
引数にuser必要ですかね？```@notification.first? || @notification.time_expired?```みたいに呼び出したいところですね。

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
>          return true
is_time_expiredっていう意味からするとここはfalseじゃないですかね？

2023-11-09 10:20 UTC, srsm2000 commented on app/models/relationship.rb
> +  # def self.follow_notification(user,current_user)
使わないコードはコメントアウトではなく基本削除してみやすくしておきましょう！（過去のコードはgithubで見れるので）

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +      if notification_first?(user) || is_time_expired?(user)
あとこのあたりの処理はsave前にできる気がしますがいかがでしょうか？結果2回saveが走っちゃっているので

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +    threshold_notification = user.notifications.where(status: 1).first
このstatus: 1ってenumで定義してますよね？その場合、1が何かわからないので定義したもので書きましょう！

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +    threshold_notification = user.notifications.where(status: 1).first
あとthresholdは伝わっていなかったので別の単語を使いましょう

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +  def self.change_hidden(user)
readという言葉を他で使っているので、mark_as_readみたいな名前がreadをupdateするんだと伝わりやすいかと！

2023-11-09 10:20 UTC, srsm2000 commented on app/models/notification.rb
> +  def is_read?
なぜ逆になっているかわかっていませんが、メソッド名的にこれは```read```と同じですかね？逆にしたければ!つければ実現できますし不要かもですね

2023-11-10 09:13 UTC, hiroshi-iwata commented on app/controllers/notifications_controller.rb
> +  before_action :correct_user, only: :index
> ※例
> 
> > 一覧なのでshowではない気がしますがいかがでしょう？
> 
> indexに変更をいたしました。

例までありがとうございます！

2023-11-10 09:15 UTC, hiroshi-iwata commented on config/routes.rb
> +  resources :notifications,       only: [:index, :update]
承知しました。
ありがとうございます！

2023-11-10 09:18 UTC, hiroshi-iwata commented on app/models/notification.rb
>    default_scope -> { order(created_at: :desc) }
承知しました。
ありがとうございます！

2023-11-10 09:19 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  }
Active Recordのクエリメソッドで表現でしました。
書いてみたらこちらの方が書きやすいことがわかりました！

2023-11-10 09:22 UTC, hiroshi-iwata commented on app/controllers/notifications_controller.rb
> +    redirect_to controller: 'notifications', action: 'index', user_id: 'notifications.user_id'
idをuser_idに変更しました。
routesで
`get '/notifications/:user_id', to:"notifications#index"`
変えたところとして、ここも変更しないといけないという認識ですが正しいでしょうか？

2023-11-10 09:26 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  }
また、userは確かに不要でした。
さらにはINTERVALは定数のためそのまま突っ込めるということがわかったので、ここには1つも引数いらなかったです…。

2023-11-10 09:28 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  def self.create_follow_notification(followed_user, follower_user)
フォローされたユーザを`followed_user`、フォローするユーザを`follower_user`としました。

2023-11-10 09:34 UTC, hiroshi-iwata commented on app/models/notification.rb
>          return true
メソッドの内容的に、「特定の時間内であるかどうか」を確かめるものなので、メソッド名の方を変更しました。

2023-11-10 09:40 UTC, hiroshi-iwata commented on app/models/relationship.rb
> +  # def self.follow_notification(user,current_user)
削除しておきました！

2023-11-10 09:52 UTC, hiroshi-iwata commented on app/models/notification.rb
>          return true
メソッドの内容的に、「特定の時間内であるかどうか」を確かめるものなので、メソッド名の方を変更しました。

2023-11-10 09:53 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  def is_read?
変更しました。
この書き方であっていますでしょうか？

2023-11-10 09:59 UTC, hiroshi-iwata commented on app/models/notification.rb
> +    first_recent_notification = user.notifications.where(status: :initial_notification).first
> このstatus: 1ってenumで定義してますよね？その場合、1が何かわからないので定義したもので書きましょう！

定義したもので書きました！

> あとthresholdは伝わっていなかったので別の単語を使いましょう

first_recent_notificationに変更しました。少し抽象的かと思いましたが、時間が明確に決められていないのでrecentにしました。

2023-11-10 10:00 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  def self.mark_as_read(user)
> readという言葉を他で使っているので、mark_as_readみたいな名前がreadをupdateするんだと伝わりやすいかと！

訂正しました！

2023-11-10 10:01 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  def is_read?
メソッド内を変更しました。
この記載であっていますでしょうか？

2023-11-13 01:22 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      if notification_first?(followed_user) || within_allowed_time?(followed_user)
> 引数にuser必要ですかね？@notification.first? || @notification.time_expired?みたいに呼び出したいところですね。

userを取らずに呼び出す方法が思いつきませんでした。
何かいい案があったら教えてもらえるとありがたいです！

2023-11-13 02:09 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      if notification_first?(followed_user) || within_allowed_time?(followed_user)
> あとこのあたりの処理はsave前にできる気がしますがいかがでしょうか？結果2回saveが走っちゃっているので

@notification.saveをした後、statusにinitial_notificationが入っていると条件式に問題が出るのでこの順番で処理をしています。

2023-11-13 05:14 UTC, srsm2000 commented on app/controllers/notifications_controller.rb
> +    redirect_to controller: 'notifications', action: 'index', user_id: 'notifications.user_id'
まさに、同じ認識です！

2023-11-13 05:15 UTC, srsm2000 commented on app/models/notification.rb
> +    first_recent_notification = user.notifications.where(status: :initial_notification).first
おっしゃる通り数値では表現でき無いのと十分伝わるのでrecent良いかと思います！

2023-11-13 05:43 UTC, srsm2000 reviewed
@hiroshi-iwata コメントしました！

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +  }
読みやすくなりました！指摘した箇所以外にも指摘内容に当てはまる箇所がある場合はそこの修正もお願いします！

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +      if notification_first?(followed_user) || within_allowed_time?(followed_user)
> user（現在のfollowed_user）を取らずにうまく呼び出す方法が思いつきませんでした。
> 何かいい案があったら教えてもらえるとありがたいです！

今notification_firstはクラスメソッドになっていますが、インスタンス変数にして@notification.first?という風に呼び出せばメソッド内でfollowed_userとかも取得出来ませんかね？

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +      if notification_first?(followed_user) || within_allowed_time?(followed_user)
> @notification.saveをした後、statusにinitial_notificationが入っていると条件式に問題が出るのでこの順番で処理をしています。

よく分かっていないので後ほど話しましょう。良いタイミングで話しかけてください

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +      if first_recent_notification.created_at <= INTERVAL
```
 if first_recent_notification
      if first_recent_notification.created_at <= INTERVAL
        return true
      else
        return false
      end
    else
      return false
    end
```

これは以下のように書き換えられます。ネストが深くならないように、何もしない条件の時は早々にreturnすると良いです。
```
return false unless first_recent_notification
first_recent_notification.created_at <= INTERVAL
```

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +  def is_read?
これもメソッド名的にreadと同じですね。つまり中身は!readではなくreadな気がします。
その場合このメソッドは不要でなはいでしょうか？

2023-11-13 05:43 UTC, srsm2000 commented on app/models/notification.rb
> +      if first_recent_notification.created_at <= INTERVAL
もっというとfirst_recent_notificationがfalseの時within_allowed_timeメソッドはfalseになりますよね？
それってメソッド名と処理の内容が一致していないのでこの中でやる処理はないですかね

2023-11-15 01:37 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      action: ['follow', 'summarize_follow']).update_all(read: true)
> 読みやすくなりました！指摘した箇所以外にも指摘内容に当てはまる箇所がある場合はそこの修正もお願いします！

修正しました！

2023-11-15 01:38 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      action: "follow").count
> 読みやすくなりました！指摘した箇所以外にも指摘内容に当てはまる箇所がある場合はそこの修正もお願いします！

修正しました！

2023-11-15 01:39 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      if @notification.first? || @notification.within_allowed_time?
> 今notification_firstはクラスメソッドになっていますが、インスタンス変数にして@notification.first?という風に呼び出せばメソッド内でfollowed_userとかも取得出来ませんかね？

Userの取り方を変えることで変更できました！
ありがとうございます！

2023-11-15 01:41 UTC, hiroshi-iwata commented
> これもメソッド名的にreadと同じですね。つまり中身は!readではなくreadな気がします。
その場合このメソッドは不要でなはいでしょうか？

メソッドにする必要がないこと理解できました！
こちらは削除しました。

2023-11-15 01:44 UTC, hiroshi-iwata commented
> よく分かっていないので後ほど話しましょう。良いタイミングで話しかけてください

> もっというとfirst_recent_notificationがfalseの時within_allowed_timeメソッドはfalseになりますよね？
それってメソッド名と処理の内容が一致していないのでこの中でやる処理はないですかね

申し訳ありません。月曜日に見ていれば直接聞けたのですが、確認が昨日になってしまっていました。
どこかのタイミングでこの2点についてお聞きできればと思っております！

2023-11-15 03:19 UTC, hiroshi-iwata commented on app/models/notification.rb
> +    end
先ほど話にあがった部分なのですが、
`oldest_within_period = followed_user.notifications.only_recent_follow.last`
この部分で`@notification.save`が必要ということに気が付きました。
その後にも`oldest_within_period.status = :initial_notification`を保存するために`oldest_within_period.save`をつけていました。
そのため、saveが2つ必要なのかと思っているのですがいかがでしょうか？

2023-11-15 03:20 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  TIME_AGO_INTERVAL = 5.minutes.ago
時間前というのを強調するため、
`TIME_AGO_INTERVAL`
と定数を命名しました。

2023-11-15 04:13 UTC, srsm2000 reviewed
コメントしました！

2023-11-15 04:13 UTC, srsm2000 commented on app/controllers/relationships_controller.rb
>      @user.notifications.where('created_at = ?', latest_created_at).update(read: false)
ここのwhereも修正できますよね、このページでwhereで全文検索すると抜け漏れ無いかと

2023-11-15 04:13 UTC, srsm2000 commented on app/models/notification.rb
> +    end
すいません！oldest_within_periodで何を処理しているかよくわからないです。@notificationとは違いますか？

2023-11-15 04:13 UTC, srsm2000 commented on app/models/notification.rb
> +  TIME_AGO_INTERVAL = 5.minutes.ago
名付に関して、全体的に英語の文法が気になるので細かいですが書いておきます！処理場問題ないので時間なければ未修正で大丈夫です。
この単語で表現するとすればTIME_INTERVAL_AGOですね

2023-11-15 04:13 UTC, srsm2000 commented on app/models/notification.rb
> +    initial_notification_recent = user.notifications.where(status: :initial_notification).first
recent_initial_notificationですね

2023-11-15 04:13 UTC, srsm2000 commented on app/models/notification.rb
> +    return true if recent_notifications_count == 1
もし事前にsaveしない場合、1ではなく0が正しいですかね

2023-11-15 15:42 UTC, hiroshi-iwata commented on app/controllers/relationships_controller.rb
> +    @user.notifications.where(created_at: latest_created_at).update(read: false)
> ここのwhereも修正できますよね、このページでwhereで全文検索すると抜け漏れ無いかと

申し訳ありません、抜け漏れでした。ファイル全てを確認するため、検索しっかりかけます！

2023-11-15 15:47 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  end
> すいません！oldest_within_periodで何を処理しているかよくわからないです。@notificationとは違いますか？

何かしたかったっぽいんですが、俣木さんの指摘通り結局@notificationと変わりませんでした。
修正しました。

また、saveの件ですが、`if @notification.first?`がtrueならsaveは後に、falseの場合は通知の順番的にsaveを先に行いたいので、各処理でsaveを入れました。

2023-11-15 15:48 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  TIME_INTERVAL_AGO = 5.minutes.ago
> 名付に関して、全体的に英語の文法が気になるので細かいですが書いておきます！処理場問題ないので時間なければ未修正で大丈夫です。
この単語で表現するとすればTIME_INTERVAL_AGOですね

修正しました！

2023-11-15 15:49 UTC, hiroshi-iwata commented on app/models/notification.rb
> +    recent_notifications_count = user.notifications.recent_follow.count
> recent_initial_notificationですね

修正しました！

2023-11-15 15:50 UTC, hiroshi-iwata commented on app/models/notification.rb
> +    return true if recent_notifications_count == 0
> もし事前にsaveしない場合、1ではなく0が正しいですかね

修正しました。
動作も問題なさそうでした！

2023-11-17 02:13 UTC, srsm2000 reviewed
大方良いかと！少しだけコメントしました。

2023-11-17 02:13 UTC, srsm2000 commented on app/models/notification.rb
> +      @notification = followed_user.notifications.new(
@notificationってインスタンス変数である必要ありますか？

2023-11-17 02:13 UTC, srsm2000 commented on app/models/notification.rb
> +  def self.create_summarize_follow(followed_user,follower_user)
これはインスタンスメソッドの方が自然だと思いますがいかがでしょうか？すると引数が不要になる気がします。

2023-11-19 05:57 UTC, hiroshi-iwata commented on app/models/notification.rb
> +      notification = followed_user.notifications.new(
> @notificationってインスタンス変数である必要ありますか？

修正しました！

2023-11-19 05:58 UTC, hiroshi-iwata commented on app/models/notification.rb
> +  def self.create_summarize_follow(followed_user,follower_user)
follower_userの情報はrelationshipのレコードにしかないのですが、引数に取らなくても値は持って来られるでしょうか？
そこがわからなかったのでとりあえずそのままにしてあります。

2023-11-20 05:21 UTC, srsm2000 commented on app/models/notification.rb
> +  def self.create_summarize_follow(followed_user,follower_user)
notificationとrelationshipって紐づいてますよね？
```
def create_summarize_follow
  follower = relationship.follower
  followed = relationship.followed
end
```

とかで取れませんか？

2023-11-20 14:47 UTC, hiroshi-iwata commented on app/models/notification.rb
> +    follower_user = relationship.follower
> notificationとrelationshipって紐づいてますよね？
> 
> def create_summarize_follow
>   follower = relationship.follower
>   followed = relationship.followed
> end
> とかで取れませんか？

ありがとうございます！取れました！

2023-11-21 02:58 UTC, srsm2000 approved these changes
お疲れ様でした！LGTMです！マージしてください。

2023-11-21 02:58 UTC, srsm2000 commented on app/models/notification.rb
> +    follower_user = relationship.follower
クラスメソッド（設計図が担うと良さそうなメソッド）とインスタンスメソッド（実体が担うとよさそうなメソッド）を意識して使い分けるようにしてみましょう。
今回は要約された通知を作るメソッドですよね。必ず一つのnotificationの実体をベースに要約通知は作られるはずなので、インスタンスメソッドが使い勝手が良さそうですね。

2023-11-21 04:55 UTC, merged